import type { Metadata } from "next"
import "./globals.css"
import Header from "@/app/components/header/Index"
import Sidebar from "@/app/components/sidebar/Index"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="w-full h-full">
      <body className="flex flex-col bg-neutral-00 p-0 m-0 h-full">
        <Header />
        <div className="flex flex-row h-full">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  )
}
